# default configuration
baseURL = "http://noel.engineer/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "noel ruault"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

# [[menu.main]]
# URL = "blog"
# name = "Blog"
# weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""

# theme color
theme_color = "#41228e"

# contact info
phone = "+34 722 122 274"
email = "contact@noel.engineer"
address = "Valencia, Spain"

# meta description
author = "Noel Ruault"
description = "Noel Ruault website. A Computer Engineer by heart."

# google analytics
google_analytics_id = "G-E0SG7RR73Y" # Your ID

# copyright
copyright = "Copyright &copy; 2021 a theme by [gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 1

# social site
[[params.social]]
icon = "ti-github"
URL = "https://github.com/noelruault"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/noelruault/"
